package es.iti.wakamiti.expressions.parser;

enum TokenType {
	NEGATION,
	START_OPTIONAL,
	END_OPTIONAL,
	CHOICE_SEPARATOR,
	START_GROUP,
	END_GROUP,
	START_ARGUMENT,
	END_ARGUMENT,
	START_SUBEXPRESSION,
	END_SUBEXPRESSION,
	TEXT,
	WILDCARD
}
