gherkin.idTagPattern:
  description: |
    Regex for tags used as identifier. If it contains a regex group, 
    only the group value would be used as identifier.
  type: text
  defaultValue: ID-(\w+)


gherkin.definitionTag:
  description: |
    Tag used to annotate a Gherkin feature as a definition node
  type: text
  constraints:
    pattern: "[\\w\\-\\_]+"
  defaultValue: definition


gherkin.implementationTag:
  description: |
    Tag used to annotate a Gherkin feature as an implementation node
  type: text
  constraints:
    pattern: "[\\w\\-\\_]+"
  defaultValue: implementation
